### PR TITLE
update symfony/http-foundation version to 3.0

### PR DESCRIPTION
**Pull request by Gorjunov**

### CODE REVIEW

**Comment by vania-pooh** [comment]
@tyz910 any ideas against merging this?

**Comment by Gorjunov** [comment]
My bad. `~` sign change is enough to support both versions

**Comment by vania-pooh** [comment]
@Gorjunov please squash two commits then.

**Comment by Gorjunov** [comment]
@vania-pooh done

**Comment by vania-pooh** [comment]
@Gorjunov thank you for contribution.

**Comment by tyz910** [comment]
:thumbsup:

**Pull request merged**
